files:
  - source: /template/template.json
    translation: /localizations/%language%.json
  - source: /template/*.json
    translation: /template/%language%/*.json
  - source: /template/extensions/*.json
    translation: /template/%language%/extensions/*.json
  - source: /template/extensions/tooltips/*.json
    translation: /template/%language%/extensions/tooltips/*.json
