files:
  - source: /template/*.json
    translation: /template/%language%/*
  - source: /template/extensions/*.json
    translation: /template/%language%/extensions/
  - source: /template/extensions/tooltips/*.json
    translation: /template/%language%/extensions/tooltips/
