name: Pull Request Test

on:
  pull_request:
    branches: [main]

jobs:
  merge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install -r ./tools/requirements.txt

      - name: run tests
        run: python -m unittest discover -s tests -p './tools/*_test.py'