name: Merge Test

on:
  pull_request:
    branches:
      - main

jobs:
  merge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python Merger-test.py

      - name: Notify success
        if: success()
        run: |
          echo "Tests passed!"
          cat "./localizations/test.json"